spring:
  datasource:
    url: jdbc:h2:file:./DB

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
